using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using WebApi.Model;

namespace WebApi.Database
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            builder.Entity<TypeProperty>().HasData(
                new TypeProperty() { TypePropertyId = 1, Name = "Unspecified" },
                new TypeProperty() { TypePropertyId = 2, Name = "Townhouse" },
                new TypeProperty() { TypePropertyId = 3, Name = "House" },
                new TypeProperty() { TypePropertyId = 4, Name = "Condominium" },
                new TypeProperty() { TypePropertyId = 5, Name = "Appartment" },
                new TypeProperty() { TypePropertyId = 6, Name = "Office" },
                new TypeProperty() { TypePropertyId = 7, Name = "Land" },
                new TypeProperty() { TypePropertyId = 8, Name = "Penthouse" },
                new TypeProperty() { TypePropertyId = 9, Name = "Serviced Apartment" },
                new TypeProperty() { TypePropertyId = 10, Name = "Shop house" },
                new TypeProperty() { TypePropertyId = 11, Name = "Retail" },
                new TypeProperty() { TypePropertyId = 12, Name = "Business" },
                new TypeProperty() { TypePropertyId = 13, Name = "Factory" },
                new TypeProperty() { TypePropertyId = 14, Name = "Commercial Building" },
                new TypeProperty() { TypePropertyId = 15, Name = "Hotel / Resort" },
                new TypeProperty() { TypePropertyId = 16, Name = "Other Commertcial" });
            builder.Entity<Improvement>().HasData(
            new Improvement() { Id = 1, Name = "Parking", Type = ImprovementType.Facilities },
            new Improvement() { Id = 2, Name = "TV", Type = ImprovementType.Facilities },
            new Improvement() { Id = 3, Name = "Refrigerator", Type = ImprovementType.Facilities },
            new Improvement() { Id = 4, Name = "Washing Machine", Type = ImprovementType.Facilities },
            new Improvement() { Id = 5, Name = "Kitchen", Type = ImprovementType.Facilities },
            new Improvement() { Id = 6, Name = "Balcony", Type = ImprovementType.Facilities },
            new Improvement() { Id = 7, Name = "Internet", Type = ImprovementType.Facilities },
            new Improvement() { Id = 8, Name = "Drying Machine", Type = ImprovementType.Facilities },
            new Improvement() { Id = 9, Name = "Private garden", Type = ImprovementType.Facilities },
            new Improvement() { Id = 10, Name = "Roof Terrace", Type = ImprovementType.Facilities },
            new Improvement() { Id = 11, Name = "Open kitchen", Type = ImprovementType.Facilities },
            new Improvement() { Id = 12, Name = "Cooker Hob & Hood", Type = ImprovementType.Facilities },
            new Improvement() { Id = 13, Name = "Closed kitchen", Type = ImprovementType.Facilities },
            new Improvement() { Id = 14, Name = "Water Heater", Type = ImprovementType.Facilities },
            new Improvement() { Id = 15, Name = "Common garden", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 16, Name = "Function Room", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 17, Name = "Common jacuzzi", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 18, Name = "Lounge", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 19, Name = "Restaurant", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 20, Name = "Building security", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 21, Name = "Garage", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 22, Name = "Onsen Spa", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 23, Name = "Sauna", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 24, Name = "Cafe", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 25, Name = "Gym/Fitness", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 26, Name = "Library", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 27, Name = "Outdoor swimming pool", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 28, Name = "Spa", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 29, Name = "Children playroom", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 30, Name = "Indoor swimming pool", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 31, Name = "Lift", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 32, Name = "Playground", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 33, Name = "Steamroom", Type = ImprovementType.CommonArea },
            new Improvement() { Id = 34, Name = "European", Type = ImprovementType.Interior },
            new Improvement() { Id = 35, Name = "Industrial", Type = ImprovementType.Interior },
            new Improvement() { Id = 36, Name = "Minimalistic", Type = ImprovementType.Interior },
            new Improvement() { Id = 37, Name = "Modern", Type = ImprovementType.Interior },
            new Improvement() { Id = 38, Name = "Thai", Type = ImprovementType.Interior },
            new Improvement() { Id = 39, Name = "Not Decorated", Type = ImprovementType.Interior },
            new Improvement() { Id = 40, Name = "Air Conditioning", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 41, Name = "Bathtub", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 42, Name = "Oven", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 43, Name = "Cooking gas", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 44, Name = "Private Pool", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 45, Name = "Fan", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 46, Name = "Stove", Type = ImprovementType.Fixtures },
            new Improvement() { Id = 47, Name = "Goverment electricity meter", Type = ImprovementType.Other },
            new Improvement() { Id = 48, Name = "Shopping Mall", Type = ImprovementType.Other },
            new Improvement() { Id = 49, Name = "Public water meter", Type = ImprovementType.Other },
            new Improvement() { Id = 50, Name = "Golf Simulator", Type = ImprovementType.Other },
            new Improvement() { Id = 51, Name = "Co-Working Space", Type = ImprovementType.Other },
            new Improvement() { Id = 52, Name = "Cleaning service", Type = ImprovementType.Other },
            new Improvement() { Id = 53, Name = "Mini Market", Type = ImprovementType.Other },
            new Improvement() { Id = 55, Name = "Wheelchair accessible", Type = ImprovementType.Extra },
            new Improvement() { Id = 56, Name = "Badminton Court", Type = ImprovementType.Extra },
            new Improvement() { Id = 57, Name = "Company Registration", Type = ImprovementType.Extra },
            new Improvement() { Id = 58, Name = "High Floor", Type = ImprovementType.Extra },
            new Improvement() { Id = 59, Name = "Low Floor", Type = ImprovementType.Extra },
            new Improvement() { Id = 60, Name = "Scenic View", Type = ImprovementType.Extra },
            new Improvement() { Id = 61, Name = "BBQ Area", Type = ImprovementType.Extra },
            new Improvement() { Id = 62, Name = "New Project", Type = ImprovementType.Extra },
            new Improvement() { Id = 63, Name = "Pool View", Type = ImprovementType.Extra },
            new Improvement() { Id = 64, Name = "Sea View", Type = ImprovementType.Extra },
            new Improvement() { Id = 65, Name = "Allows Pets", Type = ImprovementType.Extra },
            new Improvement() { Id = 66, Name = "Shuttle service", Type = ImprovementType.Extra },
            new Improvement() { Id = 67, Name = "Jogging Track", Type = ImprovementType.Extra },
            new Improvement() { Id = 68, Name = "Luxury", Type = ImprovementType.Extra },
            new Improvement() { Id = 69, Name = "Park View", Type = ImprovementType.Extra },
            new Improvement() { Id = 70, Name = "Rent Guarantee", Type = ImprovementType.Extra },
            new Improvement() { Id = 71, Name = "Allow Short-term", Type = ImprovementType.Extra },
            new Improvement() { Id = 72, Name = "City View", Type = ImprovementType.Extra },
            new Improvement() { Id = 73, Name = "Lake View", Type = ImprovementType.Extra },
            new Improvement() { Id = 74, Name = "Maid's Room", Type = ImprovementType.Extra },
            new Improvement() { Id = 75, Name = "Penthouse", Type = ImprovementType.Extra },
            new Improvement() { Id = 76, Name = "Partially Furnished", Type = ImprovementType.Basic },
            new Improvement() { Id = 77, Name = "Fully Furnished", Type = ImprovementType.Basic },
            new Improvement() { Id = 78, Name = "Needs renovation", Type = ImprovementType.Basic },
            new Improvement() { Id = 79, Name = "Renovated", Type = ImprovementType.Basic },
            new Improvement() { Id = 80, Name = "To be renovated", Type = ImprovementType.Basic },
            new Improvement() { Id = 81, Name = "Unfurnished", Type = ImprovementType.Basic },
            new Improvement() { Id = 82, Name = "Jacuzzi", Type = ImprovementType.Basic },
            new Improvement() { Id = 83, Name = "Walk-in-Wardrobe", Type = ImprovementType.Basic },
            new Improvement() { Id = 84, Name = "Maid's Room", Type = ImprovementType.Basic },
            new Improvement() { Id = 85, Name = "Tennis Court", Type = ImprovementType.Basic }

            );
            builder.Entity<Station>().HasData(
                new Station() { StationId = 1, StationType = StationType.BTSSilom, Name = "National Stadium" },
                new Station() { StationId = 2, StationType = StationType.BTSSilom, Name = "Siam" },
                new Station() { StationId = 3, StationType = StationType.BTSSilom, Name = "Ratchadamri" },
                new Station() { StationId = 4, StationType = StationType.BTSSilom, Name = "Sala Daeng" },
                new Station() { StationId = 5, StationType = StationType.BTSSilom, Name = "Surasak" },
                new Station() { StationId = 6, StationType = StationType.BTSSilom, Name = "Saphan Taksin" },
                new Station() { StationId = 7, StationType = StationType.BTSSilom, Name = "Krung Thon Buri" },
                new Station() { StationId = 8, StationType = StationType.BTSSilom, Name = "Wongwian Yai" },
                new Station() { StationId = 9, StationType = StationType.BTSSilom, Name = "Pho Nimit" },
                new Station() { StationId = 10, StationType = StationType.BTSSilom, Name = "Talat Phlu" },
                new Station() { StationId = 11, StationType = StationType.BTSSilom, Name = "Wutthakat" },
                new Station() { StationId = 12, StationType = StationType.BTSSilom, Name = "Bang Wa" },
                new Station() { StationId = 13, StationType = StationType.BTSSuk, Name = "Khu Khot" },
                new Station() { StationId = 14, StationType = StationType.BTSSuk, Name = "Yaek Kor Por Aor" },
                new Station() { StationId = 15, StationType = StationType.BTSSuk, Name = "Royal Thai Air Force Museum" },
                new Station() { StationId = 16, StationType = StationType.BTSSuk, Name = "Bhumibol Adulyadej Hospital" },
                new Station() { StationId = 17, StationType = StationType.BTSSuk, Name = "Saphan Mai" },
                new Station() { StationId = 18, StationType = StationType.BTSSuk, Name = "Sai Yud" },
                new Station() { StationId = 19, StationType = StationType.BTSSuk, Name = "Phahon Yothin 59" },
                new Station() { StationId = 20, StationType = StationType.BTSSuk, Name = "Wat Phra Sri Mahathat" },
                new Station() { StationId = 21, StationType = StationType.BTSSuk, Name = "11th Infantry Regiment" },
                new Station() { StationId = 22, StationType = StationType.BTSSuk, Name = "Bang Bua" },
                new Station() { StationId = 23, StationType = StationType.BTSSuk, Name = "Royal Forest Department" },
                new Station() { StationId = 24, StationType = StationType.BTSSuk, Name = "Kasetsart University" },
                new Station() { StationId = 25, StationType = StationType.BTSSuk, Name = "Sena Nikhom" },
                new Station() { StationId = 26, StationType = StationType.BTSSuk, Name = "Ratchayothin" },
                new Station() { StationId = 27, StationType = StationType.BTSSuk, Name = "Phahon Yothin 24" },
                new Station() { StationId = 28, StationType = StationType.BTSSuk, Name = "Ha Yaek Lat Phrao" },
                new Station() { StationId = 29, StationType = StationType.BTSSuk, Name = "Mo Chit" },
                new Station() { StationId = 30, StationType = StationType.BTSSuk, Name = "Saphan Kwai" },
                new Station() { StationId = 31, StationType = StationType.BTSSuk, Name = "Ari" },
                new Station() { StationId = 32, StationType = StationType.BTSSuk, Name = "Sanam Pao" },
                new Station() { StationId = 33, StationType = StationType.BTSSuk, Name = "Victory Monument" },
                new Station() { StationId = 34, StationType = StationType.BTSSuk, Name = "Phaya Thai" },
                new Station() { StationId = 35, StationType = StationType.BTSSuk, Name = "Ratchathewi" },
                new Station() { StationId = 36, StationType = StationType.BTSSuk, Name = "Chit Lom" },
                new Station() { StationId = 37, StationType = StationType.BTSSuk, Name = "Ploen Chit" },
                new Station() { StationId = 38, StationType = StationType.BTSSuk, Name = "Nana" },
                new Station() { StationId = 39, StationType = StationType.BTSSuk, Name = "Asok" },
                new Station() { StationId = 40, StationType = StationType.BTSSuk, Name = "Phrom Phong" },
                new Station() { StationId = 41, StationType = StationType.BTSSuk, Name = "Thong Lo" },
                new Station() { StationId = 42, StationType = StationType.BTSSuk, Name = "Ekkamai" },
                new Station() { StationId = 43, StationType = StationType.BTSSuk, Name = "Phra Khanong" },
                new Station() { StationId = 44, StationType = StationType.BTSSuk, Name = "On Nut" },
                new Station() { StationId = 45, StationType = StationType.BTSSuk, Name = "Bang Chak" },
                new Station() { StationId = 46, StationType = StationType.BTSSuk, Name = "Punnawithi" },
                new Station() { StationId = 47, StationType = StationType.BTSSuk, Name = "Udom Suk" },
                new Station() { StationId = 48, StationType = StationType.BTSSuk, Name = "Bang Na" },
                new Station() { StationId = 49, StationType = StationType.BTSSuk, Name = "Bearing" },
                new Station() { StationId = 50, StationType = StationType.BTSSuk, Name = "Samrong" },
                new Station() { StationId = 51, StationType = StationType.BTSSuk, Name = "Pu Chao" },
                new Station() { StationId = 52, StationType = StationType.BTSSuk, Name = "Chang Erawan" },
                new Station() { StationId = 53, StationType = StationType.BTSSuk, Name = "Royal Thai Naval Academy" },
                new Station() { StationId = 54, StationType = StationType.BTSSuk, Name = "Pak Nam" },
                new Station() { StationId = 55, StationType = StationType.BTSSuk, Name = "Srinagarindra" },
                new Station() { StationId = 56, StationType = StationType.BTSSuk, Name = "Phraek Sa" },
                new Station() { StationId = 57, StationType = StationType.BTSSuk, Name = "Sai Luat" },
                new Station() { StationId = 58, StationType = StationType.BTSSuk, Name = "Kheha" },
                new Station() { StationId = 59, StationType = StationType.MRT, Name = "Hua Lamphong" },
                new Station() { StationId = 60, StationType = StationType.MRT, Name = "Sam Yan" },
                new Station() { StationId = 61, StationType = StationType.MRT, Name = "Si Lom" },
                new Station() { StationId = 62, StationType = StationType.MRT, Name = "Lumphini" },
                new Station() { StationId = 63, StationType = StationType.MRT, Name = "Khlong Toei" },
                new Station() { StationId = 64, StationType = StationType.MRT, Name = "Queen Sirikit National Convention Centre" },
                new Station() { StationId = 65, StationType = StationType.MRT, Name = "Sukhumvit" },
                new Station() { StationId = 66, StationType = StationType.MRT, Name = "Phetchaburi" },
                new Station() { StationId = 67, StationType = StationType.MRT, Name = "Phra Ram 9" },
                new Station() { StationId = 68, StationType = StationType.MRT, Name = "Thailand Cultural Centre" },
                new Station() { StationId = 69, StationType = StationType.MRT, Name = "Huai Khwang" },
                new Station() { StationId = 70, StationType = StationType.MRT, Name = "Sutthisan" },
                new Station() { StationId = 71, StationType = StationType.MRT, Name = "Ratchadaphisek" },
                new Station() { StationId = 72, StationType = StationType.MRT, Name = "Lat Phrao" },
                new Station() { StationId = 73, StationType = StationType.MRT, Name = "Phahon Yothin" },
                new Station() { StationId = 75, StationType = StationType.MRT, Name = "Mo Chit" },
                new Station() { StationId = 76, StationType = StationType.MRT, Name = "Kamphaeng Phet" },
                new Station() { StationId = 77, StationType = StationType.MRT, Name = "Bang Sue" },
                new Station() { StationId = 78, StationType = StationType.MRT, Name = "Hua Lamphong" },
                new Station() { StationId = 79, StationType = StationType.MRT, Name = "Tao Poon " },
                new Station() { StationId = 80, StationType = StationType.MRT, Name = "Tha Phra" },
                new Station() { StationId = 81, StationType = StationType.MRT, Name = "Charan 13" },
                new Station() { StationId = 82, StationType = StationType.MRT, Name = "Fai Chai" },
                new Station() { StationId = 83, StationType = StationType.MRT, Name = "Bang Khun Non" },
                new Station() { StationId = 84, StationType = StationType.MRT, Name = "Bang Yi Khan" },
                new Station() { StationId = 85, StationType = StationType.MRT, Name = "Sirindhorn" },
                new Station() { StationId = 86, StationType = StationType.MRT, Name = "Bang Phlat" },
                new Station() { StationId = 87, StationType = StationType.MRT, Name = "Bang O" },
                new Station() { StationId = 88, StationType = StationType.MRT, Name = "Bang Pho" },
                new Station() { StationId = 89, StationType = StationType.MRT, Name = "Wat Mangkon" },
                new Station() { StationId = 90, StationType = StationType.MRT, Name = "Sam Yot" },
                new Station() { StationId = 91, StationType = StationType.MRT, Name = "Sanam Chai" },
                new Station() { StationId = 92, StationType = StationType.MRT, Name = "Itsaraphap" },
                new Station() { StationId = 93, StationType = StationType.MRT, Name = "Tha Phra" },
                new Station() { StationId = 94, StationType = StationType.MRT, Name = "Bang Phai" },
                new Station() { StationId = 95, StationType = StationType.MRT, Name = "Bang Wa" },
                new Station() { StationId = 96, StationType = StationType.MRT, Name = "Phetkasem 48" },
                new Station() { StationId = 97, StationType = StationType.MRT, Name = "Phasi Charoen" },
                new Station() { StationId = 98, StationType = StationType.MRT, Name = "Bang Khae" },
                new Station() { StationId = 99, StationType = StationType.MRT, Name = "Lak Song" },
                new Station() { StationId = 100, StationType = StationType.MRT, Name = "Khlong Bang Phai" },
                new Station() { StationId = 101, StationType = StationType.MRT, Name = "Talad Bang Yai" },
                new Station() { StationId = 102, StationType = StationType.MRT, Name = "Sam Yaek Bang Yai" },
                new Station() { StationId = 103, StationType = StationType.MRT, Name = "Bang Phlu" },
                new Station() { StationId = 104, StationType = StationType.MRT, Name = "Bang Rak Yai" },
                new Station() { StationId = 105, StationType = StationType.MRT, Name = "Bang Rak Noi Tha It" },
                new Station() { StationId = 106, StationType = StationType.MRT, Name = "Sai Ma" },
                new Station() { StationId = 107, StationType = StationType.MRT, Name = "Phra Nangklao Bridge" },
                new Station() { StationId = 108, StationType = StationType.MRT, Name = "Yaek Nonthaburi 1" },
                new Station() { StationId = 109, StationType = StationType.MRT, Name = "Bang Krasor" },
                new Station() { StationId = 110, StationType = StationType.MRT, Name = "Nonthaburi Civic Centre" },
                new Station() { StationId = 111, StationType = StationType.MRT, Name = "Ministry Of Public Health" },
                new Station() { StationId = 112, StationType = StationType.MRT, Name = "Yaek Tiwanon" },
                new Station() { StationId = 113, StationType = StationType.MRT, Name = "Wong Sawang" },
                new Station() { StationId = 114, StationType = StationType.MRT, Name = "Bang Son" }
            );
            builder.Entity<Project>().HasMany(c => c.Properties).WithOne(e => e.Project);
            builder.Entity<TypeProperty>().HasMany(c => c.Properties).WithOne(e => e.TypeProperties);
            builder.Entity<City>().HasMany(c => c.Properties).WithOne(e => e.City);
            builder.Entity<Province>().HasMany(c => c.Cities).WithOne(e => e.Province);
            builder.Entity<ApplicationUser>().Property(e => e.Id).ValueGeneratedOnAdd();

        }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Property> Properties { get; set; }
        public DbSet<TypeProperty> TypeProperties { get; set; }
        public DbSet<Station> Stations { get; set; }
        public DbSet<FileOnFileSystemModel> FilesOnFileSystem { get; set; }
        public DbSet<Improvement> Improvements { get; set; }
        public DbSet<ImprovementToProperty> ImprovementToProperty { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Province> Province { get; set; }
        public DbSet<Callback> Callbacks { get; set; }
        public DbSet<Owner> Owners { get; set; }
        public DbSet<Company> Companies { get; set; }

    }
}
